[book]
authors = ["Nico Jensch"]
description = "Contains the documentation for the dr460nixed flake."
language = "en"
src = "src"
title = "Dr460nixed ❄️ documentation"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "mocha"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/dr460nf1r3/dr460nixed"
site-url = "https://nixed.dr460nf1r3.org"
