---
name: Build images
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: write
on:
  push:
    branches: [main]
    paths: [home-manager, nixos, overlays, flake.lock, flake.nix]
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4
      - name: Install Nix ğŸ“¦
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011  # v23
        with:
          extra_nix_config: |
            accept-flake-config = true
            system-features = big-parallel kvm
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check flake ğŸ“
        run: nix flake check
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4
      - name: Install Nix ğŸ“¦
        uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011  # v23
        with:
          extra_nix_config: |
            accept-flake-config = true
            system-features = big-parallel kvm
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build ISO ğŸ“€
        run: nix build --accept-flake-config -L .#packages.x86_64-linux.iso
        env:
          NIXPKGS_ALLOW_UNFREE: 1
      - name: Upload ISO ğŸš€
        uses: actions/upload-artifact@v3
        with:
          name: Dr460nixed ISO
          path: result/iso/*.iso
      - name: Create release ğŸ“¦
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: result/iso/*.iso
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
